"""Add cash desk

Revision ID: 16825034de23
Revises: 4ae2c36dbb6a
Create Date: 2020-06-03 03:36:58.401695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16825034de23'
down_revision = '4ae2c36dbb6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process__purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('fp', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process__purchase_fp'), 'process__purchase', ['fp'], unique=True)
    op.add_column('purchase', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('purchase', sa.Column('fp', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_purchase_fp'), 'purchase', ['fp'], unique=True)
    op.create_foreign_key(None, 'purchase', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase', type_='foreignkey')
    op.drop_index(op.f('ix_purchase_fp'), table_name='purchase')
    op.drop_column('purchase', 'fp')
    op.drop_column('purchase', 'author_id')
    op.drop_index(op.f('ix_process__purchase_fp'), table_name='process__purchase')
    op.drop_table('process__purchase')
    # ### end Alembic commands ###
