"""Model Shop, Column Inn now  not unique

Revision ID: 26c76c04f3bb
Revises: 79d32003d075
Create Date: 2020-06-10 18:30:13.439731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26c76c04f3bb'
down_revision = '79d32003d075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shop_inn', table_name='shop')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_shop_inn', 'shop', ['inn'], unique=True)
    # ### end Alembic commands ###
