"""Update user model

Revision ID: 86819573a477
Revises: f82ce2618719
Create Date: 2020-06-06 19:22:52.448230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86819573a477'
down_revision = 'f82ce2618719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('limit_access', sa.Boolean(), nullable=True))
    op.drop_index('ix_user_role', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_role', 'user', ['role'], unique=False)
    op.drop_column('user', 'limit_access')
    # ### end Alembic commands ###
